### ISSUE TITLE
Process blocked because of Contract already deployed

### ISSUE THREAD

**Issue by redDwarf03** [archethic-foundation/erc20-atomic-swap#45]
### Describe the problem you discovered

<img width="599" alt="Capture d’écran 2023-01-31 à 10 30 37" src="https://user-images.githubusercontent.com/68340133/215721814-f0e6c16d-6416-4740-bc58-2708dcb93fdb.png">

When i met this issue, i can't restart a new process.
I should reset the local storage manually

**Comment by samuelmanzanera** [comment]
Fixed on 1f357965ae78f88d1eb020b9cef12ef9f6476ce7
